const mongoose = require('mongoose');

const sectionSchema = new mongoose.Schema(
  {
    name: { type: String, required: true }, // 'Quantitative Aptitude'
    subject: { type: String, required: true }, // 'QA'
    durationSec: { type: Number, required: true },
    marksPerQuestion: { type: Number, default: 2 },
    negativeMarks: { type: Number, default: 0.5 },
    questions: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Question', required: true }],
  },
  { _id: false },
);

const mockTestSchema = new mongoose.Schema(
  {
    title: { type: String, required: true },
    exam: { type: String, required: true, index: true },
    description: { type: String, default: '' },
    sections: { type: [sectionSchema], default: [] },
    totalQuestions: { type: Number, required: true },
    totalDurationSec: { type: Number, required: true },
    isAutoGenerated: { type: Boolean, default: false },
    isLive: { type: Boolean, default: true, index: true },
    difficultyMix: {
      easy: { type: Number, default: 0.3 },
      medium: { type: Number, default: 0.5 },
      hard: { type: Number, default: 0.2 },
    },
  },
  { timestamps: true },
);

module.exports = mongoose.model('MockTest', mockTestSchema);
