import React, { useEffect, useState } from 'react';
import { api } from '../api';

export default function MockTestsPage() {
  const [items, setItems] = useState<any[]>([]);
  const [busy, setBusy] = useState(false);

  const load = async () => {
    const r = await api.get('/mock-tests');
    setItems(r.data.items || []);
  };

  useEffect(() => {
    load();
  }, []);

  const generate = async () => {
    setBusy(true);
    try {
      await api.post('/mock-tests/auto', { exam: 'CGL' });
      await load();
    } finally {
      setBusy(false);
    }
  };

  return (
    <>
      <h1 className="h1">Mock Tests</h1>
      <div className="card">
        <p style={{ marginTop: 0 }}>
          Auto-generate a fresh CBT-style mock with 100 sampled questions across 4 sections (Reasoning, GA,
          QA, English). Curated mock tests can be created via <code>POST /v1/admin/mock-tests</code>.
        </p>
        <button onClick={generate} disabled={busy}>
          {busy ? 'Generating...' : 'Auto-generate CGL mock'}
        </button>
      </div>

      <div className="card">
        <table className="table">
          <thead>
            <tr>
              <th>Title</th>
              <th>Exam</th>
              <th>Questions</th>
              <th>Duration</th>
              <th>Source</th>
              <th>Live</th>
            </tr>
          </thead>
          <tbody>
            {items.map((m) => (
              <tr key={m._id}>
                <td>{m.title}</td>
                <td>{m.exam}</td>
                <td>{m.totalQuestions}</td>
                <td>{Math.round(m.totalDurationSec / 60)} min</td>
                <td>{m.isAutoGenerated ? 'Auto' : 'Curated'}</td>
                <td>{m.isLive ? '✓' : '—'}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </>
  );
}
