const express = require('express');
const MockTest = require('../models/MockTest');
const Question = require('../models/Question');
const asyncHandler = require('../utils/asyncHandler');
const { requireAuth } = require('../middleware/auth');

const router = express.Router();

// List published mock tests
router.get(
  '/',
  requireAuth,
  asyncHandler(async (req, res) => {
    const { exam } = req.query;
    const filter = { isLive: true };
    if (exam) filter.exam = exam;
    const items = await MockTest.find(filter)
      .select('-sections.questions')
      .sort({ createdAt: -1 })
      .lean();
    res.json({ items });
  }),
);

// Auto-generate a fresh mock test on demand
router.post(
  '/auto',
  requireAuth,
  asyncHandler(async (req, res) => {
    const { exam = 'CGL' } = req.body || {};
    const sectionsSpec = [
      { name: 'General Intelligence & Reasoning', subject: 'REASONING', count: 25, durationSec: 15 * 60 },
      { name: 'General Awareness', subject: 'GA', count: 25, durationSec: 15 * 60 },
      { name: 'Quantitative Aptitude', subject: 'QA', count: 25, durationSec: 15 * 60 },
      { name: 'English', subject: 'ENGLISH', count: 25, durationSec: 15 * 60 },
    ];

    const sections = [];
    let totalQuestions = 0;
    for (const s of sectionsSpec) {
      const sample = await Question.aggregate([
        { $match: { exam, subject: s.subject } },
        { $sample: { size: s.count } },
      ]);
      sections.push({
        name: s.name,
        subject: s.subject,
        durationSec: s.durationSec,
        marksPerQuestion: 2,
        negativeMarks: 0.5,
        questions: sample.map((q) => q._id),
      });
      totalQuestions += sample.length;
    }

    const mock = await MockTest.create({
      title: `Auto Mock — ${exam} — ${new Date().toISOString().slice(0, 10)}`,
      exam,
      description: 'Auto-generated mock test simulating real SSC CBT format.',
      sections,
      totalQuestions,
      totalDurationSec: sections.reduce((acc, s) => acc + s.durationSec, 0),
      isAutoGenerated: true,
    });
    res.status(201).json({ mockTest: mock });
  }),
);

// Full mock test with question payloads (without correctAnswer/explanation)
router.get(
  '/:id',
  requireAuth,
  asyncHandler(async (req, res) => {
    const mock = await MockTest.findById(req.params.id).lean();
    if (!mock) return res.status(404).json({ error: 'not_found' });

    const allIds = mock.sections.flatMap((s) => s.questions);
    const questions = await Question.find({ _id: { $in: allIds } })
      .select('-correctAnswer -explanation -explanationHi -tricks -solutionSteps')
      .lean();
    const qMap = new Map(questions.map((q) => [q._id.toString(), q]));
    mock.sections = mock.sections.map((s) => ({
      ...s,
      questions: s.questions.map((id) => qMap.get(id.toString())).filter(Boolean),
    }));
    res.json({ mockTest: mock });
  }),
);

module.exports = router;
