/**
 * Curated sample SSC questions used for seeding.
 * In production, the admin panel + bulk-import endpoint will populate lakhs of items.
 */
module.exports = [
  // ===== Quantitative Aptitude =====
  {
    exam: 'CGL',
    subject: 'QA',
    topic: 'Percentage',
    chapter: 'Arithmetic',
    difficulty: 'easy',
    type: 'mcq',
    question: 'If 40% of a number is 80, what is the number?',
    questionHi: 'किसी संख्या का 40% यदि 80 है, तो वह संख्या क्या है?',
    options: [
      { key: 'A', text: '160' },
      { key: 'B', text: '200' },
      { key: 'C', text: '240' },
      { key: 'D', text: '320' },
    ],
    correctAnswer: 'B',
    explanation: 'Let the number be x. 0.4x = 80 => x = 200.',
    tricks: 'Divide the value by the percentage and multiply by 100: 80 / 40 * 100 = 200.',
    solutionSteps: ['0.4x = 80', 'x = 80 / 0.4', 'x = 200'],
    isPYQ: true,
    pyqYear: 2022,
    tags: ['percentage', 'basic'],
  },
  {
    exam: 'CGL',
    subject: 'QA',
    topic: 'Time and Work',
    difficulty: 'medium',
    question:
      'A can do a piece of work in 12 days and B in 18 days. How many days will they take working together?',
    options: [
      { key: 'A', text: '6.0' },
      { key: 'B', text: '7.2' },
      { key: 'C', text: '8.4' },
      { key: 'D', text: '9.0' },
    ],
    correctAnswer: 'B',
    explanation: 'Combined 1-day work = 1/12 + 1/18 = 5/36. Days = 36/5 = 7.2.',
    tricks: 'Use LCM: assume work = LCM(12,18)=36. A=3/day, B=2/day, together=5/day → 36/5 = 7.2.',
    solutionSteps: ['Work per day = 1/12 + 1/18', '= 3/36 + 2/36 = 5/36', 'Total days = 36/5 = 7.2'],
    tags: ['time-and-work'],
  },
  {
    exam: 'CHSL',
    subject: 'QA',
    topic: 'Profit and Loss',
    difficulty: 'easy',
    question: 'A shopkeeper sells an item for ₹120 with 20% profit. The cost price is:',
    options: [
      { key: 'A', text: '₹96' },
      { key: 'B', text: '₹100' },
      { key: 'C', text: '₹110' },
      { key: 'D', text: '₹125' },
    ],
    correctAnswer: 'B',
    explanation: 'CP = SP / (1 + profit%) = 120 / 1.2 = 100.',
    tricks: 'For 20% profit, multiply SP by 5/6 to get CP.',
    tags: ['profit-loss'],
  },

  // ===== Reasoning =====
  {
    exam: 'CGL',
    subject: 'REASONING',
    topic: 'Number Series',
    difficulty: 'easy',
    question: 'Find the next number: 2, 6, 12, 20, 30, ?',
    options: [
      { key: 'A', text: '40' },
      { key: 'B', text: '42' },
      { key: 'C', text: '44' },
      { key: 'D', text: '46' },
    ],
    correctAnswer: 'B',
    explanation: 'Differences: 4, 6, 8, 10, 12 → next term = 30 + 12 = 42.',
    tricks: 'Each gap increases by 2.',
    tags: ['series'],
  },
  {
    exam: 'CHSL',
    subject: 'REASONING',
    topic: 'Coding-Decoding',
    difficulty: 'medium',
    question: "If 'CAT' is coded as 'DBU', how is 'DOG' coded?",
    options: [
      { key: 'A', text: 'EPH' },
      { key: 'B', text: 'EOH' },
      { key: 'C', text: 'DPH' },
      { key: 'D', text: 'EPI' },
    ],
    correctAnswer: 'A',
    explanation: 'Each letter shifts +1: D→E, O→P, G→H.',
    tricks: 'Treat letters as numbers; add the offset.',
    tags: ['coding'],
  },
  {
    exam: 'MTS',
    subject: 'REASONING',
    topic: 'Analogy',
    difficulty: 'easy',
    question: 'Hand : Glove :: Foot : ?',
    options: [
      { key: 'A', text: 'Sock' },
      { key: 'B', text: 'Shoe' },
      { key: 'C', text: 'Toe' },
      { key: 'D', text: 'Heel' },
    ],
    correctAnswer: 'B',
    explanation: 'Glove covers a hand; a shoe covers a foot.',
    tags: ['analogy'],
  },

  // ===== English =====
  {
    exam: 'CGL',
    subject: 'ENGLISH',
    topic: 'Synonyms',
    difficulty: 'easy',
    question: "Choose the synonym of 'Abundant':",
    options: [
      { key: 'A', text: 'Scarce' },
      { key: 'B', text: 'Plentiful' },
      { key: 'C', text: 'Tiny' },
      { key: 'D', text: 'Rare' },
    ],
    correctAnswer: 'B',
    explanation: "'Abundant' means existing in large quantities, i.e., 'plentiful'.",
    tags: ['vocabulary', 'synonym'],
  },
  {
    exam: 'CHSL',
    subject: 'ENGLISH',
    topic: 'Error Spotting',
    difficulty: 'medium',
    question: 'Identify the error: "He don\'t / like / playing cricket."',
    options: [
      { key: 'A', text: "He don't" },
      { key: 'B', text: 'like' },
      { key: 'C', text: 'playing cricket' },
      { key: 'D', text: 'No error' },
    ],
    correctAnswer: 'A',
    explanation: "Third-person singular 'He' takes 'doesn't', not 'don't'.",
    tags: ['grammar', 'subject-verb-agreement'],
  },
  {
    exam: 'MTS',
    subject: 'ENGLISH',
    topic: 'Antonyms',
    difficulty: 'easy',
    question: "Choose the antonym of 'Ancient':",
    options: [
      { key: 'A', text: 'Old' },
      { key: 'B', text: 'Modern' },
      { key: 'C', text: 'Aged' },
      { key: 'D', text: 'Antique' },
    ],
    correctAnswer: 'B',
    explanation: "Opposite of 'Ancient' is 'Modern'.",
    tags: ['vocabulary', 'antonym'],
  },

  // ===== General Awareness =====
  {
    exam: 'CGL',
    subject: 'GA',
    topic: 'Indian Polity',
    difficulty: 'easy',
    question: 'Who is known as the Father of the Indian Constitution?',
    options: [
      { key: 'A', text: 'Mahatma Gandhi' },
      { key: 'B', text: 'B. R. Ambedkar' },
      { key: 'C', text: 'Jawaharlal Nehru' },
      { key: 'D', text: 'Sardar Patel' },
    ],
    correctAnswer: 'B',
    explanation: 'Dr. B. R. Ambedkar chaired the drafting committee of the Indian Constitution.',
    isPYQ: true,
    pyqYear: 2021,
    tags: ['polity', 'history'],
  },
  {
    exam: 'CHSL',
    subject: 'GA',
    topic: 'Geography',
    difficulty: 'medium',
    question: 'The Tropic of Cancer does NOT pass through which Indian state?',
    options: [
      { key: 'A', text: 'Gujarat' },
      { key: 'B', text: 'Madhya Pradesh' },
      { key: 'C', text: 'Odisha' },
      { key: 'D', text: 'Tripura' },
    ],
    correctAnswer: 'C',
    explanation: 'The Tropic of Cancer passes through 8 Indian states; Odisha is not one of them.',
    tags: ['geography'],
  },
  {
    exam: 'GD',
    subject: 'GA',
    topic: 'Science',
    difficulty: 'easy',
    question: 'The chemical symbol of Gold is:',
    options: [
      { key: 'A', text: 'Go' },
      { key: 'B', text: 'Gd' },
      { key: 'C', text: 'Au' },
      { key: 'D', text: 'Ag' },
    ],
    correctAnswer: 'C',
    explanation: "From Latin 'Aurum'.",
    tags: ['chemistry', 'science'],
  },

  // ===== Current Affairs =====
  {
    exam: 'CGL',
    subject: 'CURRENT_AFFAIRS',
    topic: 'Sports',
    difficulty: 'easy',
    question: 'India hosted the ICC Cricket World Cup most recently in which year?',
    options: [
      { key: 'A', text: '2011' },
      { key: 'B', text: '2019' },
      { key: 'C', text: '2023' },
      { key: 'D', text: '2024' },
    ],
    correctAnswer: 'C',
    explanation: 'India hosted the ICC Men\'s Cricket World Cup in 2023.',
    tags: ['sports'],
  },
  {
    exam: 'CGL',
    subject: 'CURRENT_AFFAIRS',
    topic: 'Awards',
    difficulty: 'medium',
    question: 'The Bharat Ratna is awarded by:',
    options: [
      { key: 'A', text: 'Prime Minister' },
      { key: 'B', text: 'President of India' },
      { key: 'C', text: 'Chief Justice of India' },
      { key: 'D', text: 'Vice President' },
    ],
    correctAnswer: 'B',
    explanation: 'It is conferred by the President of India.',
    tags: ['awards'],
  },

  // ===== CPO / JE / Steno samples =====
  {
    exam: 'CPO',
    subject: 'REASONING',
    topic: 'Direction Sense',
    difficulty: 'medium',
    question: 'Ramesh walks 5 km north, then 3 km east. How far is he from the start?',
    options: [
      { key: 'A', text: '√34 km' },
      { key: 'B', text: '8 km' },
      { key: 'C', text: '2 km' },
      { key: 'D', text: '7 km' },
    ],
    correctAnswer: 'A',
    explanation: 'Distance = sqrt(5^2 + 3^2) = sqrt(34) km.',
    tags: ['direction'],
  },
  {
    exam: 'JE',
    subject: 'QA',
    topic: 'Mensuration',
    difficulty: 'medium',
    question: 'Volume of a cube of side 6 cm is:',
    options: [
      { key: 'A', text: '36 cm³' },
      { key: 'B', text: '108 cm³' },
      { key: 'C', text: '216 cm³' },
      { key: 'D', text: '512 cm³' },
    ],
    correctAnswer: 'C',
    explanation: '6 × 6 × 6 = 216.',
    tags: ['mensuration'],
  },
  {
    exam: 'STENO',
    subject: 'ENGLISH',
    topic: 'One Word Substitution',
    difficulty: 'medium',
    question: 'A person who speaks many languages is called:',
    options: [
      { key: 'A', text: 'Linguist' },
      { key: 'B', text: 'Polyglot' },
      { key: 'C', text: 'Bilingual' },
      { key: 'D', text: 'Orator' },
    ],
    correctAnswer: 'B',
    explanation: "'Polyglot' = a person who knows and uses several languages.",
    tags: ['vocabulary'],
  },
];
