/* eslint-disable no-console */
const mongoose = require('mongoose');

const env = require('../src/config/env');
const { connectDb } = require('../src/config/db');
const User = require('../src/models/User');
const Question = require('../src/models/Question');
const MockTest = require('../src/models/MockTest');
const DailyContent = require('../src/models/DailyContent');

const sampleQuestions = require('./questions.sample');

async function seedAdmin() {
  let admin = await User.findOne({ email: env.admin.email });
  if (!admin) {
    admin = new User({
      name: 'SSC Saathi Admin',
      email: env.admin.email,
      role: 'admin',
      authProviders: ['password'],
    });
    await admin.setPassword(env.admin.password);
    await admin.save();
    console.log(`[seed] admin created: ${env.admin.email} / ${env.admin.password}`);
  } else {
    console.log(`[seed] admin already exists: ${env.admin.email}`);
  }
  return admin;
}

async function seedQuestions() {
  await Question.deleteMany({ source: 'curated' });
  const docs = sampleQuestions.map((q) => ({ ...q, source: 'curated' }));
  const inserted = await Question.insertMany(docs);
  console.log(`[seed] inserted ${inserted.length} questions`);
  return inserted;
}

async function seedSampleMockTest(questions) {
  await MockTest.deleteMany({ isAutoGenerated: false });
  const subjects = ['REASONING', 'GA', 'QA', 'ENGLISH'];
  const sections = subjects.map((s) => {
    const qs = questions.filter((q) => q.subject === s).slice(0, 5);
    return {
      name: ({
        REASONING: 'General Intelligence & Reasoning',
        GA: 'General Awareness',
        QA: 'Quantitative Aptitude',
        ENGLISH: 'English Language',
      })[s],
      subject: s,
      durationSec: 15 * 60,
      marksPerQuestion: 2,
      negativeMarks: 0.5,
      questions: qs.map((q) => q._id),
    };
  });
  const mock = await MockTest.create({
    title: 'SSC CGL Sample Mock Test',
    exam: 'CGL',
    description: 'Curated sample mock to demonstrate the real CBT-style flow.',
    sections,
    totalQuestions: sections.reduce((acc, s) => acc + s.questions.length, 0),
    totalDurationSec: sections.reduce((acc, s) => acc + s.durationSec, 0),
    isAutoGenerated: false,
  });
  console.log(`[seed] created mock test: ${mock.title}`);
}

async function seedDailyContent(questions) {
  const date = new Date().toISOString().slice(0, 10);
  await DailyContent.deleteMany({ date });

  const dailyQuiz = questions.slice(0, 5).map((q) => q._id);
  await DailyContent.create({
    date,
    type: 'quiz',
    title: 'Daily SSC Quiz',
    summary: '5 quick questions to keep your prep on track.',
    questions: dailyQuiz,
  });

  await DailyContent.create({
    date,
    type: 'currentAffairs',
    title: 'Daily Current Affairs Digest',
    summary: 'Top 5 news bytes relevant for SSC exams.',
    payload: {
      articles: [
        { title: 'India hosts G20 finance ministers meet', tag: 'Polity' },
        { title: 'New ISRO mission scheduled for next quarter', tag: 'Science & Tech' },
        { title: 'GDP grows 7.2% in last quarter', tag: 'Economy' },
        { title: 'Indian athlete wins gold at international meet', tag: 'Sports' },
        { title: 'Government launches new skilling scheme', tag: 'Schemes' },
      ],
    },
  });

  await DailyContent.create({
    date,
    type: 'vocabulary',
    title: 'Word of the Day',
    summary: 'Build your English vocabulary daily.',
    payload: {
      words: [
        { word: 'Ubiquitous', meaning: 'Present everywhere', sentence: 'Smartphones are ubiquitous today.' },
        { word: 'Pragmatic', meaning: 'Practical and realistic', sentence: 'A pragmatic approach to problem-solving.' },
        { word: 'Ephemeral', meaning: 'Lasting a very short time', sentence: 'Fame can be ephemeral.' },
      ],
    },
  });

  console.log('[seed] daily content created for', date);
}

async function main() {
  await connectDb();
  await seedAdmin();
  const questions = await seedQuestions();
  await seedSampleMockTest(questions);
  await seedDailyContent(questions);
  await mongoose.disconnect();
  console.log('[seed] done');
}

main().catch((err) => {
  console.error('[seed] failed', err);
  process.exit(1);
});
